<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'utils\\' => array($baseDir . '/utils'),
    'libs\\' => array($baseDir . '/libs'),
    'config\\' => array($baseDir . '/config'),
    'Controllers\\' => array($baseDir . '/Controllers'),
);
